apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: qa
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30008
